version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=production
    ports:
      - 3000:3000
    links:
      - pg
    command: ["puma"]
    entrypoint: /app/docker-entrypoint.sh

  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data

  sidekiq:
    build: .
    command: ["sidekiq", "-C", "config/sidekiq.yml"]
    environment:
      - REDIS_URL=redis://redis:6379
      - RAILS_ENV=production
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
    depends_on:
      - app
    links:
      - pg
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis/data

volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
  redis-data: {}
